# Generated by Django 4.2.7 on 2023-12-02 05:53

import ckeditor_uploader.fields
import courses.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Атауы')),
                ('intensity', models.CharField(max_length=50, verbose_name='Қарқындылығы')),
                ('tumbnail_image', models.ImageField(upload_to=courses.models.upload_to)),
                ('description', models.TextField(verbose_name='Мәлімет')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GraphicItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Атауы')),
                ('day_order', models.PositiveIntegerField(verbose_name='Реттілігі')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Мәлімет')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graphic_items', to='courses.course')),
            ],
        ),
    ]
